---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.10.254"}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
    driver:
      customize:
        memory: 1024
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 1024

suites:
  - name: default
    data_bag_path: "test/integration/default/data_bags"
    run_list:
      - recipe[centos-test::default]
    provisioner:
      encrypted_data_bag_secret_key_path: "test/integration/default/secret_key"
    attributes:
